# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
#
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/src/cloud_functions/passport_eye_analysis"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/src/cloud_functions/export_user_data"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/src/cloud_functions/create_signed_url"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/src/cloud_functions/database_cleanup"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/src/cloud_functions/reencrypt_data"
    schedule:
      interval: "daily"
