# import third-party libraries
from pydantic import BaseModel, Field

class RecaptchaToken(BaseModel):
    recaptcha_token: str = Field(
        title="reCAPTCHA Token",
        description="The reCAPTCHA token generated by the client-side reCAPTCHA widget on the login page.",
        example="03AGdBq27tFcDrfiRuxQnyKs-SUKoNDeeZXLlpiwNsLqdm9BSQQRtxhkD...",
        min_length=1,
    )