name: Security Vulnerability
description: File a security vulnerability report here
title: "[Security Vulnerability]: (Enter a short summary of the security vulnerability here）"
labels: ["security"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this security vulnerability report! 

  - type: input
    id: commit_reference
    attributes:
      label: Commit Reference
      description: At what commit did you encounter this security vulnerability?
      placeholder: "[cd3dfed](https://github.com/Solaireis/CWC-ISPJ/commit/cd3dfed01207bfaa71c20b2ea3b7b87c749d66a6)"
    validations:
      required: true

  - type: textarea
    id: vulnerability_description
    attributes:
      label: What is the vulnerability?
      description: A clear and concise description of what the vulnerability is.
      placeholder: Passwords are stored in plaintext... etc.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (Optional)
      description: Screenshots can be uploaded by simply dragging an image file into this box
    validations:
      required: false
